### ISSUE TITLE
.NET Core 1.1 support

### ISSUE THREAD

**Issue by bartstinson** [cloudfoundry/dotnet-core-buildpack#118]
The current buildpack doesn't seem to be compatible with .NET Core 1.1 RTM ASP Web Apps. When will a new buildpack be available to support .NET Core 1.1 RTM?

**Comment by degrim** [comment]
@bartstinson Support for this was added to the release created on November 23rd, make sure that you are specifying the proper version of the tools (1.0.0-preview2-1-003177) in your global.json file.

**Comment by bartstinson** [comment]
That's a good point. I was not using global.json in my projects before. It wasn't a necessary component as I thought only project.json was necessary. 

With .NET Core 1.1, project.json is gone. Does CloudFoundry .NET Core deployment still need project.json? Because even if I specify the proper version of the tools in global.json, I still get the following error when trying to push app

/tmp/buildpacks/dotnet-core-buildpack/lib/buildpack/release/releaser.rb:26:in `release': No project could be identified to run (RuntimeError)
        from /tmp/buildpacks/dotnet-core-buildpack/lib/buildpack.rb:46:in `release'
        from /tmp/buildpacks/dotnet-core-buildpack/bin/release:26:in `<main>'
Staging failed: Release info failed:

**Comment by degrim** [comment]
.NET Core can be run using project.json or csproj, depending on which version of the .NET CLI tooling you are using.  Currently, the versions of the tooling that are supported by this buildpack are the preview2 versions which only use project.json format.  Work has begun on adding support for the new msbuild format using .csproj files instead of project.json.  If you have installed VS2017 RC, it comes with a version of the tooling which uses the .csproj format that is not compatible with this buildpack yet.  The global.json file will also work locally to specify which version of the tooling gets used when running the dotnet commands from the command-line.

**Comment by autodidaddict** [comment]
I'm trying to push an app that requires the 1.1.0 framework. This works fine locally with tools version `1.0.0-preview2-1-003177` e.g. `dotnet restore` and run... but when I push this same app to PCF, it cannot find Framework 1.1.0 installed. How do I get this to work? I have dependencies that require the 1.1.0 framwork.

**Comment by degrim** [comment]
@autodidaddict Make sure that you have a global.json file in your project which specifies `1.0.0-preview2-1-003177` as the sdk version.  Without a global.json file you'll get the latest LTS version of the runtime when using the buildpack, but you'll get the latest version that you have installed when running locally.

**Comment by degrim** [comment]
@autodidaddict [global.json reference](See https://docs.microsoft.com/en-us/dotnet/articles/core/tools/global-json) for more info on using global.json to specify the version.

**Comment by autodidaddict** [comment]
I'd just like to point out how annoying it is that SDK `1.0.0-preview2-003177` is the only one that allows you to use framework `1.1.0`. The versioning scheme for this nonsense has sucked from day 1 and continues to get worse.

I was able to get the app to work fine in the buildpack by publishing rather than letting the BP do the vendoring for me.

**Comment by degrim** [comment]
@autodidaddict I agree that the current process needs improvement and this is something that we've been discussing changing, I'll open an issue related to that change.

**Comment by degrim** [comment]
@autodidaddict I've opened #120 related to this change.

**Comment by keaty** [comment]
@autodidaddict closing this issue as related issue #120 has been resolved.
