### ISSUE TITLE
Is a .NET Core 2.0 preview version in the roadmap?

### ISSUE THREAD

**Issue by ReneHerrero** [cloudfoundry/dotnet-core-buildpack#144]
Hi,

Is a .NET Core 2.0 preview version in the roadmap?

Thanks,

**Comment by sclevine** [comment]
Now that there are supported SDK versions available, I'm not sure how we feel about including pre-release versions.

@degrim thoughts?

**Comment by ReneHerrero** [comment]
Thanks for the reply.

Here's the reasoning behind the ask:

MS recently dropped a bomb: https://github.com/aspnet/Home/issues/2022

In short, the possibility of using ASP.NET Core on top of the full .NET framework won't be an option with ASP.NET Core 2.0.  This forces a full blown adoption of .NET Core and brings on more risk.

The good news is they are very actively working on closing the gaps.  Having a 2.0 based  dotnet_code_build pack would allow us to start testing apps and pointing out the gaps we find to MS.

Make sense?

One more question which might be out of place: is a dotnet_core_buildpack for Windows Server 2016 Nano in the works?  Reason I'm asking is that some platforms do not implement all API -> these throw a PlatformNotSupportedException (or MissingMemberException in some instances) at runtime.

Thanks again for the feedback

**Comment by degrim** [comment]
@sclevine I think it would be ok to include the preview release as non-default, with a notification that this version will be replaced with the GA version when it comes rather than living side-by-side as GA releases do currently.  On the other hand, it is already possible to use any SDK version with this buildpack by just publishing the application locally as a self-contained deployment and pushing the published files.  That even works with the nightly builds of .NET Core 2.0.

**Comment by sclevine** [comment]
Seems reasonable to include it as non-default, with warning messages, for users who don't publish locally first. Story to follow is: https://www.pivotaltracker.com/story/show/145211249

**Comment by sclevine** [comment]
Released in [v1.0.20](https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v1.0.20).
