### ISSUE TITLE
.Net Core 3.0 support

### ISSUE THREAD

**Issue by andre-vw** [cloudfoundry/dotnet-core-buildpack#217]
Is there a date on the availability of the version 3.0 in the buildpack?

Thanks

**Comment by chrpai** [comment]
Is this done? I seemingly was able to use .net core 3.0 and .net sdk 3.0.100 in a manifest/buildpack.yml.  But now it looks like .net core 3.1 has been released since this was created.

**Comment by ahaleiii** [comment]
It looks like this issue was resolved with the most recent release:
https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.3.1

.NET Core 3.1 is in [preview release](https://dotnet.microsoft.com/download/dotnet-core) currently, and is scheduled for a full release [December 2019](https://dotnet.microsoft.com/platform/support/policy/dotnet-core).

**Comment by Zanadar** [comment]
Correct. This has been added to the buildpack
